name: Feature request
description: Suggest an enhancement for the AIO
title: "Sample request title"
labels: ["needs-triage"]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Description
      description: Please provide a description of the enhancement
  - type: textarea
    validations:
      required: true
    attributes:
      label: Screenshots
      description: If applicable, add screenshots here to help explain your problem
  - type: textarea
    attributes:
      label: Additional context
      description: Enter any other applicable info here
